### ISSUE TITLE
Doesn't work on linux (yet)

### ISSUE THREAD

**Issue by thecountrox** [CrafterlKrunker/NullClient#1]
![image](https://user-images.githubusercontent.com/74064922/156887027-40c1151e-c1cc-47e5-98fd-5281c5cef66f.png)
I understand that testing for linux can be a bit hard so , if you want any logs I can provide :D

**Comment by CrafterlKrunker** [comment]
Okay, for me it works on Ubuntu and also on archcraft but you are not the first one who reported this. I will try to fix that

**Comment by CrafterlKrunker** [comment]
Also try the latest version, it might be fixed

**Comment by thecountrox** [comment]
Yes the latest version is fixed , But the reCaptcha error shows up in game now :
![image](https://user-images.githubusercontent.com/74064922/157365947-d463309a-1b4f-43a2-83da-19a5dc491108.png)

**Comment by CrafterlKrunker** [comment]
I will fix that
