### ISSUE TITLE
"a javascript error occured in the main process"

### ISSUE THREAD

**Issue by ssjblue-xxx** [CrafterlKrunker/NullClient#3]
i am on mac m1 and each time i launch the client i get this erro
<img width="280" alt="Capture d’écran 2022-03-26 à 14 50 28" src="https://user-images.githubusercontent.com/76740788/160242461-1feb09bb-63bb-46b4-ae57-8972611f08f2.png">

anyone knows fixes ?

**Comment by CrafterlKrunker** [comment]
Well known problem, I am trying to fix it

**Comment by ssjblue-xxx** [comment]
@CrafterlKrunker i might know the issue, basic old macs are x64 but mac m1 (including other m1s) are aarch64

**Comment by ssjblue-xxx** [comment]
i will compile it myself and see how it goes

**Comment by ssjblue-xxx** [comment]
took me some time, but yeah the error was that it only worked on intel macs but i made my own build and now it works with some bugs like you can't open settings

**Comment by ssjblue-xxx** [comment]
nvm fixed it, solid 400 fps nice

**Comment by CrafterlKrunker** [comment]
Ah okay, so the build you did has basically outdated code but I will add aarch64 to the release
