### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by Munchax10** [CrafterlKrunker/NullClient#7]
lemonfish css and some others break the whole game. Cant change settings back because css breaks settings menu.
![image](https://user-images.githubusercontent.com/79412545/192554080-a791351f-cbfd-4541-b630-32631d378433.png)

**Comment by Munchax10** [comment]
managed to delete whole config and back to changing settings :(

**Comment by CrafterlKrunker** [comment]
fix soon
